module.exports = {
  preset: "react-native",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json"],
  transform: {
    "^.+\\.(ts|tsx|js|jsx)$": [
      "babel-jest",
      { configFile: "./babel.config.test.js" },
    ],
  },
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
  testPathIgnorePatterns: [
    "/node_modules/",
    "/android/",
    "/ios/",
    "babel.config.test.js",
  ],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@assets/(.*)$": "<rootDir>/src/assets/$1",
    "^@contexts/(.*)$": "<rootDir>/src/contexts/$1",
    "^@features/(.*)$": "<rootDir>/src/features/$1",
    "^@components/(.*)$": "<rootDir>/src/global/components/$1",
    "^@utils/(.*)$": "<rootDir>/src/global/utils/$1",
    "^@models/(.*)$": "<rootDir>/src/global/models/$1",
    "^@stores/(.*)$": "<rootDir>/src/global/stores/$1",
    "^@hooks/(.*)$": "<rootDir>/src/global/hooks/$1",
    "^@services/(.*)$": "<rootDir>/src/global/services/$1",
    "^@styles/(.*)$": "<rootDir>/src/global/styles/$1",
    "^@navigation/(.*)$": "<rootDir>/src/navigation/$1",
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  testEnvironment: "node",
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/*.d.ts",
    "!src/**/index.ts",
    "!src/**/*.stories.{ts,tsx}",
    "!src/**/*.test.{ts,tsx}",
    "!src/**/*.spec.{ts,tsx}",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  transformIgnorePatterns: [
    "node_modules/(?!(react-native|@react-native|expo|@expo|@react-navigation)/)",
  ],
  moduleDirectories: ["node_modules", "src"],
  testTimeout: 10000,
  collectCoverage: false,
};
