export const SCROLL_THRESHOLD = 400;

export const FLATLIST_CONFIG = {
  INITIAL_NUM_TO_RENDER: 10,
  MAX_TO_RENDER_PER_BATCH: 10,
  WINDOW_SIZE: 15,
  SCROLL_EVENT_THROTTLE: 16,
  DECELERATION_RATE: 0.87,
  ITEM_HEIGHT: 80,
} as const;

export const SEARCH_DEBOUNCE_MS = 450;
